run:
  dt_h: 1.0
  solver: gurobi

costs:
  include_gridcost_in_energy: true
  include_demand_charge_in_rh: true
  include_co2_cost_in_objective: true
  dump_cost_eur_per_mwh_th: 1.0
  co2_price_eur_per_t: 100.0

grid:
  energy_fee_eur_mwh: 0.0
  demand_charge_eur_per_mw_y: 120000.0
  gridcost_eur_mwh: 0.0
  sell_floor_eur_mwh: 0.0
  sell_haircut_fraction: 0.0
  sell_spread_eur_mwh: 0.0
  sell_fee_eur_mwh: 0.0
  sell_premium_eur_mwh: 0.0
  year_fraction: 1.0
  big_m_grid_mw: 10000.0
